<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartDrag.Core\SmartDrag.Core.csproj" />
    <ProjectReference Include="..\SmartDrag.Imaging\SmartDrag.Imaging.csproj" />
  </ItemGroup>
</Project>
